services:
  postgres_dw:
    image: postgres:15-alpine
    container_name: used_car_postgres_dw
    restart: always
    environment:
      POSTGRES_DB: used_car_dw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_dw_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d used_car_dw"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dw_data:
